local color = require "core.colors.palets"

-- UI highlight

hl("Directory", { fg = color.white, bg = none })

hl("DiffAdd", { fg = color.green, bg = color.background_alt })
hl("DiffChange", { fg = color.yellow_b, bg = color.background_alt })
hl("DiffDelete", { fg = color.red, bg = color.background_alt })
hl("DiffText", { fg = color.magenta, bg = color.background_alt })

hl("EndOfBuffer", { fg = none, bg = none })
hl("ErrorMsg", { fg = color.black, bg = color.red_b, underline = false })
hl("VertSplit", { fg = color.black_b, bg = color.background_alt })
hl("WinSeparator", { link = "VertSplit" })

hl("IncSearch", { fg = color.black, bg = color.yellow })

hl("MatchParen", { fg = color.white_b, bold = true })
hl("ModeMsg", { fg = color.white_b, bg = color.magenta_b })
hl("MoreMsg", { fg = color.white_b, bg = color.magenta_b })
hl("NonText", { fg = color.black })


hl("Question", { fg = color.blue, bg = color.background_alt })
hl("Search", { fg = color.black, bg = color.yellow })
hl("SpecialKey", { fg = color.black, bg = color.background_alt })
hl("Tabline", { fg = color.white, bg = color.background })
hl("TablineFill", { fg = color.white, bg = color.yellow_b })
hl("TablineSel", { fg = color.white, bg = color.background_alt })
hl("Title", { bold = true })
hl("Visual", { bg = color.black })
hl("VisualNOS", { bg = color.blue })
hl("WarningMsg", { fg = color.yellow, bold = true })

hl("WildMenu", { fg = color.black, bg = color.blue })

-- Syntax highlight
hl("Comment", { fg = color.white })
hl("Constant", { fg = color.magenta })
hl("String", { fg = color.green })
hl("Character", { fg = color.green })
hl("Number", { fg = color.green })
hl("Boolean", { fg = color.magenta_b, bold = true })
hl("Float", { fg = color.green })
hl("Identifier", { fg = color.yellow_b })
hl("Function", { fg = color.cyan })
hl("Statement", { fg = color.yellow_b, bold = true })
hl("Conditional", { fg = color.yellow_b, bold = true })
hl("Repeat", { fg = color.yellow_b, bold = true })
hl("Label", { fg = color.magenta_b })
hl("Operator", { fg = color.magenta_b })
hl("Keyword", { fg = color.yellow_b, bold = true })
hl("Exception", { fg = color.yellow_b, bold = true })
hl("PreProc", { fg = color.yellow_b })
hl("Include", { fg = color.yellow_b })
hl("Define", { fg = color.yellow_b, bold = true })
hl("Macro", { fg = color.yellow_b })
hl("PreCondit", { fg = color.yellow_b, bold = true })
hl("Type", { fg = color.cyan })
hl("StorageClass", { fg = color.yellow_b, bold = true })
hl("Structure", { fg = color.magenta, bold = true })
hl("TypeDef", { fg = color.green_b, bold = true })
hl("Special", { fg = color.blue })
hl("SpecialChar", { fg = color.blue })
hl("Tag", { fg = color.green })
hl("Delimiter", { fg = color.green })
hl("SpecialComment", { fg = color.black, bold = true })
hl("Debug", { fg = color.yellow })
hl("Underlined", { underline = true })
hl("Ignore", { fg = color.white_b })
hl("Error", { fg = color.red_b, underline = true })
hl("SpellBad", { fg = color.red_b, underline = true, sp = color.red })
hl("SpellCap", { fg = color.red, underline = true, sp = color.red })
hl("SpellRare", { fg = color.red, underline = true, sp = color.red })
hl("SpellLocale", { fg = color.red, underline = true, sp = color.red })
hl("Todo", { fg = color.yellow, bold = true })
hl("Whitespace", { fg = color.background })

-- Treesitter highlight
hl("@text.literal", { fg = color.white })
hl("@text.title", { fg = color.green, bold = true })
hl("@text.emphasis", { fg = color.green, italic = true })
hl("@text.strong", { fg = color.green, bold = true })
hl("@text.uri", { fg = color.blue, underline = true })
hl("@text.todo", { fg = color.yellow, bold = true })
hl("@text.note", { fg = color.green, bold = true })
hl("@comment", { fg = color.white })
hl("@constant", { fg = color.magenta })
hl("@string", { fg = color.green })
hl("@number", { fg = color.cyan })
hl("@function", { fg = color.blue })
hl("@variable", { fg = color.white })
hl("@type", { fg = color.green })

-- LSP Semantic Tokens
hl("@lsp.type.class", { link = "@type" })
hl("@lsp.type.function", { link = "@function" })
hl("@lsp.type.method", { link = "@function" })
hl("@lsp.type.macro", { link = "@macro" })
hl("@lsp.type.variable", { link = "@variable" })
